name: Build and Deploy to Cloud Run

on:
  push:
    branches:
        - main

# Environment variables available to all jobs and steps in this workflow
env:
    PROJECT_ID: collegeproject-380416
    SERVICE_NAME: test1
    REGION: asia-south1
    
jobs:
    setup-build-deploy:
        name: Setup, Build, and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            # Setup gcloud CLI
            - id: 'auth'
              uses: 'google-github-actions/auth@v0'
              with:
                credentials_json: '${{ secrets.GCP_SA_KEY }}'
            # Configure gcloud CLI
            - name: gcloud Set up
              run: |
                  gcloud config set project $PROJECT_ID
      
            - name: Image
              run: |-
                docker build -t asia.gcr.io/$PROJECT_ID/$SERVICE_NAME .
                
            #Configure docker to use the gcloud command-line tool as a credential helper
            - run: |
                  gcloud auth configure-docker -q
              # Push image to Google Container Registry
            - name: Build
              run: |-
                  docker push asia.gcr.io/$PROJECT_ID/$SERVICE_NAME
            - name: Deploy
              run: |
                  gcloud run deploy $SERVICE_NAME --region $REGION --image asia.gcr.io/$PROJECT_ID/$SERVICE_NAME --allow-unauthenticated